### ISSUE TITLE
Running application fails with "Configuration with name 'default' not found."

### ISSUE THREAD

**Issue by rmilesson** [reime005/react-native-tapjoy#1]
After installing this module via the manual instructions (up to and including point 6) and trying to run my application I get the following error

    FAILURE: Build failed with an exception.

    * What went wrong:
    A problem occurred configuring project ':app'.
    > Could not resolve all dependencies for configuration ':app:_debugApk'.
    > Configuration with name 'default' not found.

Automatic installation is not an option for me.
RN version 0.46.4

Any thoughts on what's wrong?

**Comment by reime005** [comment]
Something might be wrong with your settings.gradle file

**Comment by rmilesson** [comment]
I'm sorry for the late answer. We had to progress with more important matters in our app. Now Tapjoy is back on the table again and I saw you've made some releases since last. Still, same error for me though:

```
09:53	Gradle sync failed: Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :react-native-tapjoy.
			Consult IDE log for more details (Help | Show Log) (4s 121ms)
```

I can't see any issues in my settings.gradle file and we're using a bunch of other modules and they work great.

Edit: I'm using gradle 3.3, is that the problem perhaps?

**Comment by reime005** [comment]
The new version should fix this issue hopefully
