### ISSUE TITLE
react-native-tapjoy should be updated quickly.

### ISSUE THREAD

**Issue by kimho** [reime005/react-native-tapjoy#11]
Tapjoy Android SDK 12.4.1 version update is required by February 29th of this year.

Tapjoy will be included in Google Play self-certified ad networks program on March 1st of this year.
However, Google Play requested some modifications to the Tapjoy SDK code for policy reasons.
So Tapjoy has released the 12.4.1 version SDK.

Therefore, Please update react-native-tapjoy to support Tapjoy Android sdk 12.4.1 version.

**Comment by reime005** [comment]
@kimho thanks for notifying. is it enough to bump the version to 12.4.1 or is there any breaking API change that you know of?

**Comment by kimho** [comment]
@reime005  
In my opinion, updating to support 12.4.1 sdk should be fine.

However, if an app is using tapjoy video through mediation, the app update schedule should refer to the schedule when the mediation will support 12.4.1 sdk.
The 12.4.1 sdk support schedule for each mediation can be found below.

[Mediator Adapter Versions](https://dev.tapjoy.com/mediator-adapter-versions/?utm_source=hs_email&utm_medium=email&utm_content=82552784&_hsenc=p2ANqtz-99FlFxgQV5MLY-_7cg6fqXaJpT9x4YrpzaxSQb1qrvOpKJiqZFZoS7l00mh6Kpzu7CiC8T9MgDSzrNYnKws2C-i9njXw&_hsmi=82552784)

**Comment by reime005** [comment]
@kimho 2.3.0 includes the 12.4.1 update

**Comment by kimho** [comment]
@reime005 Thank you very much!
