### ISSUE TITLE
Once again, react-native-tapjoy should be updated!

### ISSUE THREAD

**Issue by kimho** [reime005/react-native-tapjoy#12]
I received the following email from the Tapjoy.
It should be updated once more to the version that supports Tapjoy Android SDK **12.4.2** (not 12.4.1).
Please check the information below and do a quick update.

> We are reaching out to request that you update the Tapjoy Android SDK to version 12.4.2 or newer as soon as possible (by March 1st, 2020 at the latest) to avoid a potential suspension by Google; please note that this policy will affect all apps live with Google as of March 1st. 
> 
> Please note that during the initial implementation process of the 12.4.1+ SDK, we uncovered a crash scenario under unreliable network conditions and therefore have immediately pushed a new version, SDK 12.4.2, to ensure no further action is required on your part.
> 
> What has changed in the new SDK?
> 
> In line with current platform requirements relating to user permissions, we have deprecated legacy code relating to install attributions in our SDK. Per clarification from Google, we recommend that all publishers upgrade to the current SDK now to avoid potential suspension of your app with connection with the use of prior versions containing the deprecated code.  
> 
> We apologize for any inconvenience this may cause.  
> 
> You can download the updated SDK here. 
> 
> In the case of mediation, we are actively working with our mediator partners to update to the latest SDK adaptor version; please click here to view the current status. 
> 
> Thank you,
> Tapjoy Developer Relations Team

Thank you for your efforts.

**Comment by reime005** [comment]
okay
