### ISSUE TITLE
Using own placement names in the example app raises a RedBox

### ISSUE THREAD

**Issue by MattHall** [reime005/react-native-tapjoy#3]
Changing the example to use the ios API key for my account, and modifying the index.common.js file so that I use my own placement names causes the app to return the following error:

```
`QuestListItem` is not a supported event type for TapjoyModule. Supported events are: `earnedCurrency`, `Offerwall`, `placementEvent`
```
Changed code is in the `tapjoyAddPlacement` method:
```
this.tapjoy.addPlacement("QuestListItem", function (evt) {
```

As far as I understand from [the docs][1], this should take the name of the placement - is that not the case?

Should probably also mention that this is a User Initiated placement.

[1]:https://github.com/reime005/react-native-tapjoy#add-placement

**Comment by reime005** [comment]
I'm sorry for that, I created this repo mostly for myself, this is why it might not be very customizable. I may forgot to document this feature - the easiest solution for now is to open TapjoyModule.m and add every placement by name to the events array. For example:

`- (NSArray<NSString *> *)supportedEvents {
  return @[TJ_EARNED_CURRENCY_EVENT, TJ_PLACEMENT_OFFERWALL_EVENT, @"placementEvent", @"QuestListItem"];
}`

I remember that it was the easiest solution for me - if I have time, I will work on it.

**Comment by MattHall** [comment]
Cheers @reime005 - I'll take a look 👍
